---
abstract: 'European CPAN authors'
author:
  - 'Abigail <cpan@abigail.be>'
build_requires:
  Acme::CPANAuthors: 0
  ExtUtils::MakeMaker: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
keywords: []
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-European
no_index:
  directory:
    - t
    - inc
requires:
  Acme::CPANAuthors::Austrian: 0
  Acme::CPANAuthors::British: 0
  Acme::CPANAuthors::French: 0
  Acme::CPANAuthors::German: 0
  Acme::CPANAuthors::Icelandic: 0
  Acme::CPANAuthors::Norwegian: 0
  Acme::CPANAuthors::Portuguese: 0
  Acme::CPANAuthors::Register: 0
  Acme::CPANAuthors::Russian: 0
  Acme::CPANAuthors::Turkish: 0
  Acme::CPANAuthors::Ukrainian: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/Abigail/Acme--CPANAuthors--European.git
version: 2014051201
