--- #YAML:1.0
name:               Acme-CPANAuthors-European
version:            2009110201
abstract:           European CPAN authors
author:
    - Abigail <cpan@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Acme::CPANAuthors:    0
    ExtUtils::MakeMaker:  0
    strict:               0
    Test::More:           0
    warnings:             0
requires:
    Acme::CPANAuthors::Austrian:  0
    Acme::CPANAuthors::French:  0
    Acme::CPANAuthors::German:  0
    Acme::CPANAuthors::Icelandic:  0
    Acme::CPANAuthors::Italian:  0
    Acme::CPANAuthors::Norwegian:  0
    Acme::CPANAuthors::Portuguese:  0
    Acme::CPANAuthors::Register:  0
    Acme::CPANAuthors::Russian:  0
    Acme::CPANAuthors::Turkish:  0
    Acme::CPANAuthors::Ukrainian:  0
    perl:                 5.006
    strict:               0
    warnings:             0
resources:
    repository:  git://github.com/Abigail/Acme--CPANAuthors--European.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:  []
